### ISSUE TITLE
Add AUX_HEATING switch option

### ISSUE THREAD

**Issue by AlbertRizzo** [kovapatrik/homebridge-midea-platform#64] opened 2024-01-18 12:07 UTC
When used with a Midea Heat Pump the plugin reports that it does not support the AUX_HEATING attribute:
[homebridge-midea-platform] [net_ac_3234] Attempt to set unsupported attribute AUX_HEATING to false

It would be very useful to add this switch option allowing the user to set Auxiliary Heating to ON or OFF.

**Comment by kovapatrik** [comment] 2024-01-18 13:24
Heat pump is currently not supported, I think the charecteritics of a heat pump is not the same as a dehumifider or an air conditioner.

Could you please provide informations about the heat pump? Which informations you can read/need, what can you control, etc...

**Comment by AlbertRizzo** [comment] 2024-01-18 16:01
Thank you for replying so quickly.
I just ran a device discovery from the plugin and this is what it returned
for my heat pump:
[18/01/2024, 08:49:53] [Homebridge UI] [homebridge-midea-platform]
Discovered device:
{"ip":"192.168.50.39","port":6444,"id":150633093369528,"model":"00000Q1B","sn":"000000P0000000Q1B096EA9032340000","name":"net_ac_3234","type":172,"version":3}

In HomeBridge it shows up as an Air Conditioner and the following
functionality works properly in the Apple Home app:

   - Shows and can set Cool/Heat mode (with the exception of Auxiliary Heat
   modes)
   - Shows and can set "Fan only" mode
   - Shows and can set Fan Speed
   - Shows and can set Target temperature
   - Shows current temperature, both for the Indoor unit and the Outdoor
   unit

My Midea heat pump (rebadged as Moovair) has a built-in electric heat coil
which can be used as an auxiliary source of heat if needed ("Aux & Heat"
mode). It can also run exclusively on auxiliary heat ("Aux" mode) or set to
never use the auxiliary heat ("Heat" mode). Please see attached screenshot
from the MSmartHome app (now called Smart Home) showing these two
additional operating modes.

The only thing missing from the way the plugin works right now is to
include two additional modes of operation to the list of operating modes:

   - Aux
   - Aux & Heat

A nice to have would be to show when the heat pump is actually using
Auxiliary Heat when in "Aux & Heat" mode. I believe that the MSmartHome app
can show this.

Please let me know if I can help in any way.
Thanks
Albert

**Comment by kovapatrik** [comment] 2024-01-18 21:14
Hm, interesting that it shows up as an air conditioner as Midea has an explicit "Heat Pump" device type.

I think you have forgotten to attach the photos, can you please reupload them? Also can you please tell me the exact name of your device?

The list which shows the available mode is limited as far as I know (so I can only filter the Apple supported type of modes, like heat or cool, and cannot add a new one), but I will test it.

**Comment by AlbertRizzo** [comment] 2024-01-18 21:47
Sorry, I replied directly in GMail and the attachment shows there but not here in GitHub. I'm attaching it here...
![IMG_1513](https://github.com/kovapatrik/homebridge-midea-platform/assets/4650334/91c00ee3-3cf8-4c9b-83a9-f5663ecef9d5)

The exact name of my heat pump is "Moovair Electric Heat Pump Model DMA24HOS20230E7 with Moovair Air Handler FMA24HIAHUU230X7". It came with a KJR-120N Wired Thermostat which I connected to my network and to the Midea cloud.

That's weird about the Heat Pump device type. I think they're just treating it as an Air Conditioner but including "Heat" as a valid mode. Strange.

One idea for the Apple modes would be to treat Auxiliary as an additional switch, similar to "Fan Only". So, if the Apple mode is "Heat", the new "Auxiliary" switch would indicate "Heat" mode (if OFF) or "Aux & Heat" mode (if ON). Of course this leaves out "Aux" mode (Auxiliary heat only). Maybe in this case the Apple supported mode could be "OFF" and the Auxiliary switch "ON"?

**Comment by kovapatrik** [comment] 2024-01-18 23:34
Okay, I think the theromstat is a generic device (so it can be used for an air conditioner as well), that's why it's exposed as an air conditioner, but I don't know why isn't it a thermostat at this point. What type the Midea app displays for the device? Is it a heat pump in the application as well?

This looks like an edge case to me, but maybe it can be handled. The auxillary switch could be an option. Btw can you set your heat pump to `cool` mode? Or only heat, aux, aux+heat is possible?

**Comment by AlbertRizzo** [comment] 2024-01-19 00:29
The Midea app shows it as an Air Conditioner device type. No mention of heat pump except that it shows all the heat modes.
Yes, the heat pump can definitely be used in cool mode as an Air Conditioner and can also be set to Auto where it automatically switches from heat to cool modes as needed.

**Comment by kovapatrik** [comment] 2024-01-19 01:42
Ah okay, it all makes sense now. One more question: in your first message you've sent the AUX_HEATING attribute. How does the log looks like if you push on Aux or Aux+Heat options? I want to find out which settings should be handled in both cases, so could you please test this?

**Comment by AlbertRizzo** [comment] 2024-01-19 09:32
Finally got some time to test.

Set mode to "Aux":
[19/01/2024, 03:26:46] [homebridge-midea-platform] [net_ac_3234] Attempt to set unsupported attribute SMART_EYE to true

Set mode to "Aux & Heat":
[19/01/2024, 03:27:18] [homebridge-midea-platform] [net_ac_3234] Attempt to set unsupported attribute SMART_EYE to false
[19/01/2024, 03:27:18] [homebridge-midea-platform] [net_ac_3234] Attempt to set unsupported attribute AUX_HEATING to true

Set mode back to "Heat":
[19/01/2024, 03:27:40] [homebridge-midea-platform] [net_ac_3234] Attempt to set unsupported attribute AUX_HEATING to false

**Comment by kovapatrik** [comment] 2024-01-19 09:53
Cool, thank you! I will try to implement this by the end of the week.

**Comment by AlbertRizzo** [comment] 2024-01-19 10:37
Hopefully this means that SMART_EYE is used to indicate when the electrical Auxiliary heating is actually being used.

In the first test when I set it to "Aux" it would be true since it's being forced to use it. When I then set it to "Aux & Heat" it wasn't cold enough outside for it to need to supplement with Auxiliary heat so I'm hoping that's why it set SMART_EYE to false. Hopefully in "Aux & Heat" mode it would switch SMART_EYE between true and false when it actually uses/stops using Auxiliary heat.

I don't have a way to test it until it actually gets cold enough outside though since the heat pump is a "Cold Climate" model which is handling -15C outside without needing Auxiliary heat.

**Comment by kovapatrik** [comment] 2024-01-19 10:44
I would assume that the SMART_EYE attribute just set the heat pump to automatically turn off/on the auxillary heating based on the temperature, so the attribute itself won't jumps from true to false. If what you describe would be true, how could be the feature itself turned on or off?

**Comment by AlbertRizzo** [comment] 2024-01-19 11:10
Good point.
So I tested it again but this time I set it first to "Aux & Heat":
[19/01/2024, 04:57:03] [homebridge-midea-platform] [net_ac_3234] Attempt to set unsupported attribute AUX_HEATING to true

Then I set it to "Aux":
[19/01/2024, 04:57:23] [homebridge-midea-platform] [net_ac_3234] Attempt to set unsupported attribute AUX_HEATING to false
[19/01/2024, 04:57:41] [homebridge-midea-platform] [net_ac_3234] Attempt to set unsupported attribute SMART_EYE to true

Then I set it back to "Heat":
[19/01/2024, 04:57:54] [homebridge-midea-platform] [net_ac_3234] Attempt to set unsupported attribute SMART_EYE to false

So it seems that:
- SMART_EYE=true & AUX_HEATING=false -> Aux mode
- SMART_EYE=false & AUX_HEATING=true -> Aux & Heat mode
- SMART_EYE=false & AUX_HEATING=false -> Heat and other modes (no Aux)
- SMART_EYE=true & AUX_HEATING=true -> Hopefully means that it's using Auxiliary heat while in Aux & Heat mode

**Comment by kovapatrik** [comment] 2024-02-25 21:46
In the next version this will be added. I will let you know when it's released.

**Comment by AlbertRizzo** [comment] 2024-02-25 21:57
> In the next version this will be added. I will let you know when it's released.

That's awesome thanks!

**Comment by kovapatrik** [comment] 2024-03-17 14:53
I've released the version which includes this feature, can you test it out please?

**Comment by AlbertRizzo** [comment] 2024-03-17 18:09
Thanks Patrik. So far I've tested setting "AUX" mode and "AUX&HEAT" mode from the Smart Home app and they both reflect correctly in Apple Home.
However, when I turned "AUX&HEAT" mode from ON to OFF using the Apple Home app it seems to have turned the heatpump completely off. Apple Home still thinks it's on but the heatpump is actually off.

**Comment by kovapatrik** [comment] 2024-03-17 18:14
Can you please send me some logs about this? Don't forget to turn on the `Enable verbose logging` options in the settings.

**Comment by AlbertRizzo** [comment] 2024-03-17 18:46
Please see my comments embedded in the logs below:

> [17/03/2024, 13:36:13] [homebridge-midea-platform] Restarting Process...
> [17/03/2024, 13:36:14] [homebridge-midea-platform] Launched child bridge with PID 20279
> [17/03/2024, 13:36:14] Registering platform 'homebridge-midea-platform.midea-platform'
> [17/03/2024, 13:36:14] [homebridge-midea-platform] Loaded homebridge-midea-platform v1.0.0 child bridge successfully
> [17/03/2024, 13:36:14] Loaded 1 cached accessories from cachedAccessories.0E3667187BA8.
> [17/03/2024, 13:36:15] [homebridge-midea-platform] Loading accessory from cache: net_ac_3234
> [17/03/2024, 13:36:15] [homebridge-midea-platform] Start device discovery...
> [17/03/2024, 13:36:15] Homebridge v1.7.0 (HAP v0.11.1) (homebridge-midea-platform) is running on port 50097.
> [17/03/2024, 13:36:15] [homebridge-midea-platform] Discovered device: {"ip":"192.168.50.39","port":6444,"id":150633093369528,"model":"00000Q1B","sn":"MYSERIALNUMBER","name":"net_ac_3234","type":172,"version":3}
> [17/03/2024, 13:36:15] [homebridge-midea-platform] [Moovair] Restoring existing accessory from cache: net_ac_3234
> [17/03/2024, 13:36:15] [homebridge-midea-platform] [Moovair] Cached device, using token/key from config file
> [17/03/2024, 13:36:15] [homebridge-midea-platform] [Moovair] Starting network listener.
> [17/03/2024, 13:36:16] [homebridge-midea-platform] This plugin generated a warning from the characteristic 'Rotation Speed': characteristic was supplied illegal value: number 999 exceeded maximum of 102. See https://homebridge.io/w/JtMGR for more info.
> [17/03/2024, 13:36:16] [homebridge-midea-platform] This plugin generated a warning from the characteristic 'Rotation Speed': characteristic was supplied illegal value: number 999 exceeded maximum of 102. See https://homebridge.io/w/JtMGR for more info.
> [17/03/2024, 13:36:18] [homebridge-midea-platform] [Moovair] Status change: {"POWER":true,"MODE":4,"TARGET_TEMPERATURE":20,"FAN_SPEED":60,"SWING_VERTICAL":false,"SWING_HORIZONTAL":false,"AUX_HEATING":true,"SCREEN_DISPLAY":true,"INDOOR_TEMPERATURE":24,"OUTDOOR_TEMPERATURE":7}
> [17/03/2024, 13:36:18] [homebridge-midea-platform] [Moovair] Status change: {"TOTAL_ENERGY_CONSUMPTION":0,"CURRENT_ENERGY_CONSUMPTION":0}
> [17/03/2024, 13:36:23] [homebridge-midea-platform] All configured devices added to Homebridge
> [17/03/2024, 13:36:49] [homebridge-midea-platform] [Moovair] Status change: {"INDOOR_TEMPERATURE":23}

I turned AUX & HEAT from ON to OFF using Apple's Home app which also turned the heat pump off:
> [17/03/2024, 13:37:53] [homebridge-midea-platform] [Moovair] Set device attribute POWER to: false
> [17/03/2024, 13:37:53] [homebridge-midea-platform] [Moovair] Set device attribute AUX_HEATING to: false
> [17/03/2024, 13:37:54] [homebridge-midea-platform] [Moovair] Status change: {"AUX_HEATING":true,"SCREEN_DISPLAY":false}
> [17/03/2024, 13:37:55] [homebridge-midea-platform] [Moovair] Status change: {"AUX_HEATING":false}
> [17/03/2024, 13:37:56] [homebridge-midea-platform] [Moovair] Status change: {"INDOOR_HUMIDITY":0}

I turned the heat pump back on using the SmartHome app:
> [17/03/2024, 13:38:20] [homebridge-midea-platform] [Moovair] Status change: {"AUX_HEATING":true}
> [17/03/2024, 13:38:26] [homebridge-midea-platform] [Moovair] Status change: {"POWER":true}
> [17/03/2024, 13:38:30] [homebridge-midea-platform] [Moovair] Status change: {"AUX_HEATING":false}
> [17/03/2024, 13:38:51] [homebridge-midea-platform] [Moovair] Status change: {"SCREEN_DISPLAY":true}

**Comment by kovapatrik** [comment] 2024-03-18 01:01
Can you tell me what the expected behaviour is? I still don't understand the problem you've got.

**Comment by AlbertRizzo** [comment] 2024-03-18 10:57
Ideally if AUX or AUX&HEAT are turned OFF from ON then it should be set back to HEAT mode and POWER stays on. In both AUX and AUX&HEAT modes the heat pump is supplying heat so if a user turns them OFF from ON they would want it to continue to supply heat not to turn off.
If it's not possible to do this, then the fact that POWER is now off should be displayed so apps like Apple Home would reflect that. Currently when I turned AUX&HEAT mode from ON to OFF in the Apple Home app the app showed that the heatpump was still on when in fact it was off.

**Comment by kovapatrik** [comment] 2024-03-18 11:25
Ah, I see. It's possible to do what you described.

**Comment by kovapatrik** [comment] 2024-03-18 11:33
Do you know how to install a plugin using the command line?

**Comment by AlbertRizzo** [comment] 2024-03-18 11:43
> Do you know how to install a plugin using the command line?

I can access the command line but I would need the exact command to use

**Comment by kovapatrik** [comment] 2024-03-18 12:36
Okay, so first thing first, delete the currently installed version of my plugin. Then in the command line insert the following one by one:

1. `git clone https://github.com/kovapatrik/homebridge-midea-platform.git`
2. `git switch fix/aux`
3. `npm i`
4. `npm run build`

Then restart Homebridge, the plugin should appear now in your plugin list with the version v1.0.1. You can test the aux switches after this.

**Comment by kovapatrik** [comment] 2024-03-18 16:24
Ah, I forgot a command. Run `cd homebridge-midea-platform` before running `git switch fix/aux`.
Also, after the `npm run build` command you also have to run `npm link .`. You might get an error for it, in that case you have to run `sudo npm link .`.

**Comment by AlbertRizzo** [comment] 2024-03-18 17:15
Great thanks.
Do I also need to run `hb-service add homebridge-midea-platform`?

**Comment by AlbertRizzo** [comment] 2024-03-19 18:53
> Great thanks. Do I also need to run `hb-service add homebridge-midea-platform`?

Please ignore my last question. I should have been in the `/var/lib/homebridge/node_modules` directory before cloning the repository. I have now installed v1.0.1 correctly and will start to test with verbose logging enabled

**Comment by AlbertRizzo** [comment] 2024-03-19 19:14
I started with the heatpump in HEAT mode and wanted to test changing to AUX mode.

I first used the **SmartHome** app to change to AUX and the logs showed:
`[19/03/2024, 13:58:10] [homebridge-midea-platform] [Moovair] Status change: {"SMART_EYE":true,"INDOOR_TEMPERATURE":22,"OUTDOOR_TEMPERATURE":1}`
Soon after I used SmartHome to change it back to HEAT and the logs showed:
`[19/03/2024, 13:58:53] [homebridge-midea-platform] [Moovair] Status change: {"SMART_EYE":false}`

I then used the **Apple Home** app to change to AUX mode and the logs showed:
`[19/03/2024, 13:59:57] [homebridge-midea-platform] [Moovair] Set device attribute SMART_EYE to: true
[19/03/2024, 13:59:57] [homebridge-midea-platform] [Moovair] Set device attribute AUX_HEATING to: false
[19/03/2024, 13:59:57] [homebridge-midea-platform] [Moovair] Status change: {"SMART_EYE":false}`
Also, the heatpump automatically cancelled AUX mode (see last log entry) and went back to HEAT mode

**Comment by kovapatrik** [comment] 2024-03-19 19:33
Could you please also write down what is the expected behavious in these cases? I don't know what the flow is with the device, it's really hard to develop it without having such a device.

**Comment by AlbertRizzo** [comment] 2024-03-19 19:55
> Could you please also write down what is the expected behavious in these cases? I don't know what the flow is with the device, it's really hard to develop it without having such a device.

The expected behaviour is exactly what your code is instructing: set SMART_EYE to true and set AUX_HEATING to false. However, the heatpump responds by setting SMART_EYE to false instead.

I wonder if it has anything to do with sending it two commands in rapid succession? Is it possible to send a single command with multiple status changes? While using the **SmartHome** app I've noticed log entries with multiple status attribute changes like this one: `[Moovair] Status change: {"SMART_EYE":false,"AUX_HEATING":true}`

**Comment by kovapatrik** [comment] 2024-03-19 22:47
Currently it's not possible, but I thought about one thing, I will push that change tomorrow, I would ask for your assistance in testing it, if it's okay for you.

**Comment by AlbertRizzo** [comment] 2024-03-19 23:35
Of course I would be happy to help test it.
I really do appreciate the work you are doing on this plugin!

**Comment by kovapatrik** [comment] 2024-03-21 09:11
I've pushed the new changes. In this cases you have to do the following:

1. go to the directory of the plugin
2. git fetch
3. git pull
4. npm run build

**Comment by AlbertRizzo** [comment] 2024-03-21 16:20
I just updated it and did some preliminary testing, turning modes On and Off with both the SmartHome and Apple Home apps and it now works as expected with both apps showing the correct current mode.
Bravo!

**Comment by kovapatrik** [comment] 2024-04-06 20:32
I've released this fix with version v1.0.1. Could you please also test this with the live version?

**Comment by AlbertRizzo** [comment] 2024-04-06 22:27
> I've released this fix with version v1.0.1. Could you please also test this with the live version?

I uninstalled the plugin and installed the official v1.0.1. I'll let you know if I notice any issues

**Comment by kovapatrik** [comment] 2024-04-06 23:02
Thank you! I will close the issue, please reopen it if you notice something.

**Closed by kovapatrik** 2024-04-06 23:02 UTC
Labels: enhancement
