### ISSUE TITLE
When switching the mode from 'Off' to 'Cool' in Homekit, AC not open

### ISSUE THREAD

**Issue by fantasy194** [kovapatrik/homebridge-midea-platform#99] opened 2024-08-05 08:01 UTC
**Describe The Bug:**

When attempting to activate the air conditioner from HomeKit (by turning it on within HomeKit, switching from 'off' to 'cool'), the unit emits a sound but fails to start up. In HomeKit, the status briefly shows as 'on' for 1-2 seconds before automatically reverting to 'off'. This issue does not occur immediately after Homebridge has been launched but starts to appear approximately 10 minutes into its operation. Additionally, while the air conditioner is already turned on, switching modes within HomeKit functions correctly; the problem only arises when trying to switch modes from an 'off' state.

**To Reproduce:**

1.Start HomeBridge application 
2.Wait almost 10mins 
3.Swith the AC mode in Homekit from 'off' to 'cool' or 'auto'

**Expected behavior:**

AC turning on and set to cool mode correctly

**Logs:**

```
[8/5/2024, 3:37:54 PM] [midea-platform] [北卧室空调] Set device attribute MODE to: 2
[8/5/2024, 3:37:54 PM] [midea-platform] [北卧室空调] Set device attribute POWER to: true
[8/5/2024, 3:37:55 PM] [midea-platform] [北卧室空调] Status change: {"POWER":false,"SCREEN_DISPLAY":false}
[8/5/2024, 3:37:55 PM] [midea-platform] [北卧室空调] Status change: {"FULL_DUST":false}
[8/5/2024, 3:38:00 PM] [midea-platform] [北卧室空调] Status change: {"FULL_DUST":true}
```
**Plugin Config:**

```json
{
    "devices": [
        {
            "type": "Air Conditioner",
            "name": "南卧室空调",
            "id": 20890**************961455,
            "advanced_options": {
                "token": "9594aa2bbbb0a0cc2e931675bef2e80aef785f12fb6*************************************290077d2628aba47167a55beaad1227f3c",
                "key": "0d88af6a6726474c838*************************************a689fc8ea99161a6295",
                "verbose": true
            },
            "AC_options": {
                "audioFeedback": true,
                "displaySwitch": {
                    "flag": false
                },
                "tempStep": 0.5
            }
        },
        {
            "type": "Air Conditioner",
            "name": "北卧室空调",
            "id": 20890**************0961478,
            "advanced_options": {
                "token": "26c07e4e85fcf566af95cd7e29907737abdc8bf004dd871*************************************947fb97b784d947e578e27d91a6e0782163e",
                "key": "c85eee1a57a14db586*************************************9e8b7f701fbdd8e121",
                "verbose": true
            },
            "AC_options": {
                "audioFeedback": true,
                "displaySwitch": {
                    "flag": false
                },
                "tempStep": 0.5
            }
        },
        {
            "type": "Air Conditioner",
            "name": "客厅空调",
            "id": 21110**************15864,
            "advanced_options": {
                "token": "7c5f69a5f0fa09052d2a0c8d1bb126d0b74ea0be4229f6fdcd5f160*************************************06191592d71a511b80eb5ce044b58873b8eddb2e0",
                "key": "74a99093abca*************************************5a854a45a4ff2ba450433f1037910",
                "verbose": true
            },
            "AC_options": {
                "audioFeedback": true,
                "displaySwitch": {
                    "flag": false
                },
                "tempStep": 0.5
            }
        },
        {
            "type": "Air Conditioner",
            "name": "阳台卧室空调",
            "id": 2100**************589075,
            "advanced_options": {
                "token": "9505b057fdff7070d502797fcd*************************************85e98625a457385b188cf1b55132f645a2",
                "key": "c9834c840be3*************************************854d5f41a0bd2446247e9971f9",
                "verbose": true
            },
            "AC_options": {
                "audioFeedback": true,
                "displaySwitch": {
                    "flag": false
                },
                "tempStep": 0.5
            }
        }
    ],
    "platform": "midea-platform"
}
```

**Screenshots:**

![cbb2a2a011fc7e434c7b722301f83e1](https://github.com/user-attachments/assets/567acd21-7760-4ca5-aeff-b8086551dbb7)

**Environment:**

- **Plugin Version**: Tried v1.1.1 and v1.1.2-beta.3
- **Homebridge Version**:  v1.8.4
- **Node.js Version**: v20.15.0
- **NPM Version**: 
- **Operating System**: Raspbian

**Comment by kovapatrik** [comment] 2024-08-05 09:30
If it works at the start but not later and there are no errors or warnings displayed, I don't know what the problem is. It might be some network issues but I don't know how we should unravel it.

**Comment by fantasy194** [comment] 2024-08-05 10:54
I recently attempted a few more times, and it seems my earlier description that restarting would solve the issue might be inaccurate, as now even restarting doesn't switch modes. I'm wondering if we could add a logic that checks the current power status before executing the mode switch. If the power is on, it should switch modes directly; if the power is off, it should turn on the power first and then switch modes. According to the current logs, it appears that when switching modes in the Apple Home app, the plugin executes the mode switch before turning on the power. I’m thinking if this process could be reversed.
```
[8/5/2024, 6:38:34 PM] [midea-platform] [北卧室空调] Set device attribute MODE to: 1
[8/5/2024, 6:38:34 PM] [midea-platform] [北卧室空调] Set device attribute POWER to: true
[8/5/2024, 6:38:34 PM] [midea-platform] [北卧室空调] Status change: {"POWER":false,"FAN_SPEED":101,"SCREEN_DISPLAY":false}
[8/5/2024, 6:38:34 PM] [midea-platform] [北卧室空调] Status change: {"INDOOR_HUMIDITY":0}
[8/5/2024, 6:38:34 PM] [midea-platform] [北卧室空调] Status change: {"FULL_DUST":false}
[8/5/2024, 6:38:46 PM] [midea-platform] [北卧室空调] Set device attribute MODE to: 2
[8/5/2024, 6:38:46 PM] [midea-platform] [北卧室空调] Set device attribute POWER to: true
[8/5/2024, 6:38:46 PM] [midea-platform] [北卧室空调] Status change: {"POWER":false,"FAN_SPEED":102,"SCREEN_DISPLAY":false,"FULL_DUST":true}
[8/5/2024, 6:38:46 PM] [midea-platform] [北卧室空调] Status change: {"FULL_DUST":false}
[8/5/2024, 6:38:51 PM] [midea-platform] [北卧室空调] Set device attribute MODE to: 2
[8/5/2024, 6:38:51 PM] [midea-platform] [北卧室空调] Set device attribute POWER to: true
[8/5/2024, 6:38:51 PM] [midea-platform] [北卧室空调] Status change: {"POWER":false,"SCREEN_DISPLAY":false,"FULL_DUST":true,"OUTDOOR_TEMPERATURE":33}
[8/5/2024, 6:38:51 PM] [midea-platform] [北卧室空调] Status change: {"FULL_DUST":false}
[8/5/2024, 6:38:58 PM] [midea-platform] [北卧室空调] Status change: {"FULL_DUST":true}
```

**Comment by fantasy194** [comment] 2024-08-05 10:54
Could it be an issue with concurrency where the mode and power commands are sent asynchronously at the same time, causing the device to miss executing a command?

**Comment by kovapatrik** [comment] 2024-08-05 10:56
Hm yeah, maybe its possible. I will publish a fix for this in the afternoon. I will let you know when it's out.

**Comment by fantasy194** [comment] 2024-08-05 11:02
> Hm yeah, maybe its possible. I will publish a fix for this in the afternoon. I will let you know when it's out.

oh I'm really grateful for the fix 😊

**Comment by kovapatrik** [comment] 2024-08-05 19:33
I've released `v1.1.2-beta.4`, could you please try it with this version?

**Comment by fantasy194** [comment] 2024-08-06 02:29
> I've released `v1.1.2-beta.4`, could you please try it with this version?

Good morning from China! I have tried version `v1.1.2-beta.4`, and I have some good news:  It's working now 😁. The mode switch operates from 'Off' to 'Cool' normally in HomeKit, but I'm a little confused about why the POWER ON command needs to be sent twice?

```
[8/6/2024, 10:15:02 AM] [midea-platform] All configured devices added to Homebridge
[8/6/2024, 10:15:10 AM] [midea-platform] [北卧室空调] Set device attribute POWER to: true
[8/6/2024, 10:15:10 AM] [midea-platform] [北卧室空调] Set device attribute POWER to: true
[8/6/2024, 10:15:10 AM] [midea-platform] [北卧室空调] Set device attribute MODE to: 2
[8/6/2024, 10:15:11 AM] [midea-platform] [北卧室空调] Status change: {"INDOOR_HUMIDITY":0}
[8/6/2024, 10:15:11 AM] [midea-platform] [北卧室空调] Status change: {"FULL_DUST":false}
[8/6/2024, 10:15:25 AM] [midea-platform] [北卧室空调] Status change: {"FULL_DUST":true}
[8/6/2024, 10:15:33 AM] [midea-platform] [北卧室空调] Set device attribute POWER to: false
[8/6/2024, 10:15:34 AM] [midea-platform] [北卧室空调] Status change: {"FULL_DUST":false}
[8/6/2024, 10:15:56 AM] [midea-platform] [北卧室空调] Status change: {"FULL_DUST":true,"INDOOR_TEMPERATURE":35}

[8/6/2024, 10:19:23 AM] [midea-platform] [北卧室空调] Set device attribute POWER to: true
[8/6/2024, 10:19:23 AM] [midea-platform] [北卧室空调] Set device attribute POWER to: true
[8/6/2024, 10:19:23 AM] [midea-platform] [北卧室空调] Set device attribute MODE to: 2
[8/6/2024, 10:19:25 AM] [midea-platform] [北卧室空调] Status change: {"FULL_DUST":false}
[8/6/2024, 10:19:25 AM] [midea-platform] [北卧室空调] Status change: {"FULL_DUST":true}
[8/6/2024, 10:19:25 AM] [midea-platform] [北卧室空调] Status change: {"OUTDOOR_TEMPERATURE":37}
[8/6/2024, 10:19:26 AM] [midea-platform] [北卧室空调] Status change: {"FULL_DUST":false}
```

**Comment by kovapatrik** [comment] 2024-08-06 09:12
I'm glad to hear it! I will check the code again, maybe there is a logic which I just copy-pasted by me from the original Python repository.

**Comment by fantasy194** [comment] 2024-08-08 02:08
> I'm glad to hear it! I will check the code again, maybe there is a logic which I just copy-pasted by me from the original Python repository.

If you need more test. I'm glad to help 🙂

**Comment by kovapatrik** [comment] 2024-08-20 14:15
I'll reopen this as the duplicated attribute change should not happen.

**Comment by kovapatrik** [comment] 2024-08-26 21:45
With the latest beta I've made the handling of sending the messages to the device much better. Can you please check if the duplication still there in the logs?

**Comment by kovapatrik** [comment] 2024-08-26 21:47
(by the way, the POWER command is duplicated because when I set the mode on the device, I also send the POWER command, but after a user sets the mode of the device, HomeKit sends the POWER command by default, so now I handled this by not sending the commands which are already in the current state of the device)

**Comment by fantasy194** [comment] 2024-08-29 02:40
Sorry for the delay. It seems to be working normally now. If the status is 'on', no more commands will be sent to the AC for now. Thanks again!😂
```
[8/29/2024, 10:32:40 AM] [midea-platform] All configured devices added to Homebridge
[8/29/2024, 10:32:59 AM] [midea-platform] [北卧室空调] Set device attribute POWER to: true
[8/29/2024, 10:32:59 AM] [midea-platform] [北卧室空调] Attribute MODE already set to 2
[8/29/2024, 10:32:59 AM] [midea-platform] [北卧室空调] Attribute POWER already set to true
[8/29/2024, 10:33:00 AM] [midea-platform] [北卧室空调] Status change: {"INDOOR_HUMIDITY":0}
----------------------------------------------------------------------------------------------
[8/29/2024, 10:35:15 AM] [midea-platform] [北卧室空调] Attribute POWER already set to true
[8/29/2024, 10:35:15 AM] [midea-platform] [北卧室空调] Set device attribute MODE to: 1
[8/29/2024, 10:35:15 AM] [midea-platform] [北卧室空调] Attribute POWER already set to true
[8/29/2024, 10:35:15 AM] [midea-platform] [北卧室空调] Status change: {"FAN_SPEED":101}
[8/29/2024, 10:35:37 AM] [midea-platform] [北卧室空调] Status change: {"INDOOR_TEMPERATURE":30}
[8/29/2024, 10:35:47 AM] [midea-platform] [北卧室空调] Set device attribute POWER to: false
[8/29/2024, 10:35:53 AM] [midea-platform] [北卧室空调] Set device attribute POWER to: true
[8/29/2024, 10:35:53 AM] [midea-platform] [北卧室空调] Set device attribute MODE to: 2
[8/29/2024, 10:35:53 AM] [midea-platform] [北卧室空调] Attribute POWER already set to true
[8/29/2024, 10:35:53 AM] [midea-platform] [北卧室空调] Status change: {"FAN_SPEED":102}
[8/29/2024, 10:36:24 AM] [midea-platform] [北卧室空调] Set device attribute POWER to: false
[8/29/2024, 10:36:24 AM] [midea-platform] [北卧室空调] Status change: {"OUTDOOR_TEMPERATURE":32.5}
```

**Closed** 2024-08-29 11:48 UTC
Labels: bug
