### ISSUE TITLE
Remove Swing and Child Lock options from Dehumidifier (never used)

### ISSUE THREAD

**Issue by simplytoast1** [kovapatrik/homebridge-midea-platform#47] opened 2023-11-17 18:00 UTC
**Is your feature request related to a problem? Please describe:**

I am nit sure if this is a HomeKit limitation but I was wondering if it would be possible to hide the humidify option on a dehumidifier.

**Describe the solution you'd like:**

Just to present options the dehumidifier has.

**Describe alternatives you've considered:**

Ignore it.

**Additional context:**

This is no means a bug and likely is a HomeKit issue but was wondering with code if you could hide or instruct HomeKit that the dehumidifier has no humidity option.

**Comment by kovapatrik** [comment] 2023-11-17 18:08
@dkerr64 

I think it's possible because of lines https://github.com/kovapatrik/homebridge-midea-platform/blob/main/src/accessory/DehumidifierAccessory.ts#L55-L57. The question is, how we want to seperate humidify and dehumidify? Is you dehumidifer capable of doing both?

**Comment by simplytoast1** [comment] 2023-11-17 18:10
Mine is not.  Perhaps it can be under advanced settings that you can set that feature flag.

**Comment by kovapatrik** [comment] 2023-11-17 18:11
Yeah I thought so because you opened the issue:D I meant to ask @dkerr64

**Comment by dkerr64** [comment] 2023-11-17 21:23
I see the same thing, I will try @kovapatrik suggestion and see if that removes the humidifier options from HomeKit.

**Comment by dkerr64** [comment] 2023-11-18 01:06
The "valid values" for TargetHumidifierDehumidifierState do not have any impact on how Homebridge or Apple Home apps show the dehumidifier.  Both continue to show Auto, Humidify and Dehumidify in their user interface.  At least with the Apple Home app if you try and select anything other than Dehumidify the user interface "resets" the selection to Dehumidify.

I also tested the Eve app and the Controller for HomeKit app.  The Eve app behaves just the same as Apple Home app.  The Controller app just shows "dehumidifying" for target state, but does not allow you to change that... whether valid values is set to all three, or just dehumidify.

There is an advantage to changing the lines that @kovapatrik pointed out.  As currently coded the plugin permits the apps to send a "auto" or "humidify" target state, and that results in this error to log...

`[11/17/2023, 8:00:42 PM] [homebridge-midea-platform] This plugin threw an error from the characteristic 'Target Humidifier-Dehumidifier State': Unhandled error thrown inside write handler for characteristic: Device net_a1_363A (150633093209019) can only be a DeHumidifier, illegal value: 0. See https://homebridge.io/w/JtMGR for more info.`

So I think it would be best to change the valid values to only "dehumidifier" but don't expect this to change the user interface in the Apple Home app.

**Comment by kovapatrik** [comment] 2023-11-19 12:02
@simplytoast1 With the latest version you should experience the same usage as @dkerr64 wrote above. Can you confirm this? If yes, can this issues be closed?

**Comment by simplytoast1** [comment] 2023-12-11 03:20
I can confirm in iOS 17.2 the “humidity” characteristics are hidden.

Is there a way to potentially hide oscillate as well?

**Comment by dkerr64** [comment] 2023-12-11 14:34
Good to hear that this is fixed by Apple in 17.2.  I have not installed it as I am unable to install betas.

Yes we can hide swing/oscillate too.  I'm wondering whether to just remove it completely or make it optional.  Are there any dehumidifiers with this feature?  I doubt it?

This also raises the question of child lock.  That similarly does nothing for me, though the API accepts it, and immediately resets it to off.

@kovapatrik thoughts?

**Comment by simplytoast1** [comment] 2023-12-11 14:36
To chime in from a user perspective:

re: Child Lock - I would hide it as well.

re: Oscillate - There are no models that I can find that support that option

I defer to you both for the design choices.

**Comment by dkerr64** [comment] 2023-12-12 02:43
PR #54 ready for review.

Please note comments in that PR about what I had to do to make the swing/lock characteristics go away for existing users that have cached accessory.

@simplytoast1 when you first restart this plugin you should see a message to log...

`New dehumidifier service version, replacing cached version.`

It should only ever appear once, the very first time you restart this plugin and then never again (well, until I make another breaking change).

Also, FYI, iOS 17.2 was released today and the options to select auto/humidifier are gone for me too.

**Comment by simplytoast1** [comment] 2023-12-12 02:45
Great news all around.  Waiting to see the new version of the plugin published.  You all should get this verified.  This is a great plugin!

**Comment by dkerr64** [comment] 2023-12-14 23:11
@kovapatrik I noticed when I restarted this in my production host that the info log message reporting
```
[12/14/2023, 6:06:21 PM] [homebridge-midea-platform] [Dehumidifier] New dehumidifier service version.
          Upgrade from vundefined to v1.
```
is now split across two lines. That wasn't the intent... is caused by line-to-long prettier [here](https://github.com/kovapatrik/homebridge-midea-platform/blob/df5143b70ccce64b60d9b1ea2f37820a80cb65a3/src/accessory/DehumidifierAccessory.ts#L44).

No urgency, but next time we're touching the code I'd like to put that back to a single line.

**Comment by kovapatrik** [comment] 2023-12-14 23:13
I thought about this when I wrote that part. I didn't know if it will be a new line or no, but yeah, this is the correct behaviour I guess. I will do an issue for this so we won't forget about it.

**Comment by kovapatrik** [comment] 2024-02-25 21:55
@dkerr64 Can I close this issue?

**Comment by dkerr64** [comment] 2024-02-26 07:52
> @dkerr64 Can I close this issue?

Yes can close.  Thanks.

**Closed** 2024-03-10 11:28 UTC
Labels: enhancement
